### ISSUE TITLE
NTF training terminated and only 4 output files generated

### ISSUE THREAD

**Issue by ozlembahar** [Lan-lab/SIGNET#1] opened 2022-02-24 09:23 UTC
Hi,

Thanks a lot for a very clear workflow. I am excited to apply this tool to my work however after binarization step I got warnings and errors and I guess ntf training step was terminated. It seems 4 out of 6 output files were generated. I could not figure out what was the reason and would appreciate any help or suggestion.

Please find the outputs and the warnings text file attached.

Best,
bahar

[gene_ntf.csv](https://github.com/Lan-lab/SIGNET/files/8131224/gene_ntf.csv)
[gene_tf.csv](https://github.com/Lan-lab/SIGNET/files/8131226/gene_tf.csv)
[data_ntf_binary.txt](https://github.com/Lan-lab/SIGNET/files/8131227/data_ntf_binary.txt)
[data_tf_binary.txt](https://github.com/Lan-lab/SIGNET/files/8131227/data_tf_binary.txt)
[warnings.txt](https://github.com/Lan-lab/SIGNET/files/8131227/warnings.txt)

**Comment by luoqh17** [comment] 2022-02-25 02:42
Did you use OS X system to run this code?
 If so,this problem seems to be caused by threading corrupt between pytorch and the OS system you used.
I am not sure how we can go about debugging this.
Here, I found a similar problem link might help you.
https://github.com/icaros-usc/pyribs/issues/175

**Comment by luoqh17** [comment] 2022-03-04 09:17
If you have no other problems, I will close this problem

**Closed as completed by luoqh17** 2022-03-04 09:17 UTC
